"""init schema

Revision ID: 0db8a12f5088
Revises: 
Create Date: 2026-05-21 15:08:00.388607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0db8a12f5088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_winners')
    op.drop_constraint(op.f('unique_participant_per_event'), 'entries', type_='unique')
    op.add_column('events', sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('auto_pick_winner', sa.Boolean(), nullable=True))
    op.add_column('participants', sa.Column('win_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_participants_normalized_username'), table_name='participants')
    op.create_index(op.f('ix_participants_normalized_username'), 'participants', ['normalized_username'], unique=True)
    op.create_index(op.f('ix_participants_username'), 'participants', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_username'), table_name='participants')
    op.drop_index(op.f('ix_participants_normalized_username'), table_name='participants')
    op.create_index(op.f('ix_participants_normalized_username'), 'participants', ['normalized_username'], unique=False)
    op.drop_column('participants', 'win_count')
    op.drop_column('events', 'auto_pick_winner')
    op.drop_column('events', 'scheduled_end')
    op.drop_column('events', 'scheduled_start')
    op.create_unique_constraint(op.f('unique_participant_per_event'), 'entries', ['event_id', 'participant_id'], postgresql_nulls_not_distinct=False)
    op.create_table('event_winners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('selection_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rerolled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_winners_event_id_fkey')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('event_winners_participant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_winners_pkey'))
    )
    # ### end Alembic commands ###
