"""add is_overflow to entries

Revision ID: 1558cc40e696
Revises: aa8c319e841f
Create Date: 2026-05-26 14:56:20.090885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1558cc40e696'
down_revision: Union[str, Sequence[str], None] = 'aa8c319e841f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_winners')
    op.add_column('entries', sa.Column('is_overflow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'is_overflow')
    op.create_table('event_winners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('selection_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rerolled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_winners_event_id_fkey')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('event_winners_participant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_winners_pkey'))
    )
    # ### end Alembic commands ###
