"""add missing columns

Revision ID: aa8c319e841f
Revises: 0db8a12f5088
Create Date: 2026-05-26 11:47:32.744510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa8c319e841f'
down_revision: Union[str, Sequence[str], None] = '0db8a12f5088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_winners')
    op.add_column('events', sa.Column('is_started', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('is_stopped', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('winner_selected', sa.Boolean(), nullable=True))
    op.add_column('participants', sa.Column('last_win_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'last_win_at')
    op.drop_column('events', 'winner_selected')
    op.drop_column('events', 'is_stopped')
    op.drop_column('events', 'is_started')
    op.create_table('event_winners',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('selection_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rerolled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_winners_event_id_fkey')),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], name=op.f('event_winners_participant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_winners_pkey'))
    )
    # ### end Alembic commands ###
